include $(top_srcdir)/tests/media/101greatgoals.mk
include $(top_srcdir)/tests/media/1tvru.mk
include $(top_srcdir)/tests/media/ardmediathek.mk
include $(top_srcdir)/tests/media/arte.mk
include $(top_srcdir)/tests/media/audioboo.mk
include $(top_srcdir)/tests/media/bikeradar.mk
if WITH_FIXME
include $(top_srcdir)/tests/media/break.mk
endif
include $(top_srcdir)/tests/media/cbsnews.mk
if WITH_FIXME
include $(top_srcdir)/tests/media/charlierose.mk
endif
include $(top_srcdir)/tests/media/clipfish.mk
include $(top_srcdir)/tests/media/dailymotion.mk
include $(top_srcdir)/tests/media/funnyordie.mk
include $(top_srcdir)/tests/media/gaskrank.mk
include $(top_srcdir)/tests/media/guardian.mk
include $(top_srcdir)/tests/media/ina.mk
include $(top_srcdir)/tests/media/lego.mk
include $(top_srcdir)/tests/media/liveleak.mk
include $(top_srcdir)/tests/media/myspass.mk
include $(top_srcdir)/tests/media/publicsenat.mk
include $(top_srcdir)/tests/media/sapo.mk
include $(top_srcdir)/tests/media/senat.mk
include $(top_srcdir)/tests/media/sevenload.mk
include $(top_srcdir)/tests/media/soundcloud.mk
include $(top_srcdir)/tests/media/spiegel.mk
include $(top_srcdir)/tests/media/ted.mk
include $(top_srcdir)/tests/media/theonion.mk
include $(top_srcdir)/tests/media/tvlux.mk
include $(top_srcdir)/tests/media/videa.mk
include $(top_srcdir)/tests/media/vimeo.mk
include $(top_srcdir)/tests/media/youtube.mk
