include $(top_srcdir)/tests/media/academicearth.mk
include $(top_srcdir)/tests/media/arte.mk
include $(top_srcdir)/tests/media/audioboo.mk
include $(top_srcdir)/tests/media/break.mk
include $(top_srcdir)/tests/media/cbsnews.mk
include $(top_srcdir)/tests/media/charlierose.mk
include $(top_srcdir)/tests/media/dailymotion.mk
include $(top_srcdir)/tests/media/funnyordie.mk
include $(top_srcdir)/tests/media/gaskrank.mk
include $(top_srcdir)/tests/media/publicsenat.mk
include $(top_srcdir)/tests/media/senat.mk
include $(top_srcdir)/tests/media/sevenload.mk
include $(top_srcdir)/tests/media/soundcloud.mk
include $(top_srcdir)/tests/media/vimeo.mk
include $(top_srcdir)/tests/media/youtube.mk
