include $(top_srcdir)/tests/media/academicearth.mk
include $(top_srcdir)/tests/media/arte.mk
include $(top_srcdir)/tests/media/audioboo.mk
include $(top_srcdir)/tests/media/break.mk
include $(top_srcdir)/tests/media/dailymotion.mk
include $(top_srcdir)/tests/media/gaskrank.mk
include $(top_srcdir)/tests/media/soundcloud.mk
include $(top_srcdir)/tests/media/vimeo.mk
include $(top_srcdir)/tests/media/youtube.mk
