=head1 NAME

libquvi-scripts - Overview of query media library scripts

=head1 DESCRIPTION

libquvi-scripts contains the embedded lua scripts that libquvi uses for
parsing the media details. Some additional utility scripts are also
included.

=head2 Documentation

E<lt>http://quvi.sourceforge.net/doc/E<gt>

=head1 WWW

 Home  : <http://quvi.sourceforge.net>
 gitweb: <http://repo.or.cz/w/libquvi-scripts.git>

=head1 LICENSE

libquvi-scripts is free software, licensed under the LGPLv2.1+.

=head1 SEE ALSO

C<libquvi(3)>, C<quvi(1)>

=head1 AUTHOR

Toni Gundogdu E<lt>legatvs at sign gmail comE<gt>

Thanks to all those who have contributed to the project by sending patches,
reporting bugs and writing feedback. You know who you are.
